"""Update is_active col to status

Revision ID: e6ae2d9f0694
Revises: 400f39737b6d
Create Date: 2025-02-04 20:48:21.353831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ae2d9f0694'
down_revision: Union[str, None] = '400f39737b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='userstatus'), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', postgresql.ENUM('ACTIVE', 'INACTIVE', 'DELETED', name='userstatus'), autoincrement=False, nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
